### ISSUE TITLE
ui_ground_hud_buttonbar_skinned.inc -- CRASH

### ISSUE THREAD

**Issue by PoPoWanObi** [twistedatrocity/SWG-Mods#1]
Using a NGE client, this is the only file that causes the client to straight up crash when loading into the game. The rest of the UI looks nice though, well done.

**Comment by PoPoWanObi** [comment]
Something in space does also, haven't bothered looking into what it is yet tho.

**Comment by twistedatrocity** [comment]
Need more info. I use this mod daily, it is also the ONLY mod I use and I experience no crashing.
